### ISSUE TITLE
Proposal: Prefer full CSS classes over & class

### ISSUE THREAD

**Issue by wuz** [lessonly/lessonly.github.io#112]
In SCSS, the ampersand allows you to reference the selector you are currently nested in using the `&`. That allows you to do stuff like this:

```scss
.some-class {
	&:hover {
		color: red;
	}
}
```

which compliles to:

```scss
.some-class:hover {
	color: red;
}
```

It has a lot of superpowers, but a good number of them lead to confusing CSS structures. One I see us use a lot is this:

```scss
.some-class {
	&-modifier {
		color: red;
	}
}
```

which compiles to 

```scss
.some-class-modifier {
	color: red;
}
```

This is a neat feature and can be used to get some interesting effects, especially with CSS naming conventions like BEM or OOCSS.

The problem is that it makes it really hard to find a class, especially in a large file with lots of selectors. If I am looking at the Javascript and see a component with a class `.some-class-modifier`, I can't just search for that string. I have to search for `.some-class`, find where that component's styles are declared, and then search for `&-modifier`. 

I'd like to recommend that we add the following rule to the SCSS/CSS styleguide:

### Prefer fully qualified selector names to `&` based selectors

I'd love to hear any thoughts anyone has!

**Comment by armilam** [comment]
Oooh, I like this. I agree that it's frustrating not to be able to search for what you're looking for in the codebase because it's been split or otherwise modified.

I've seen this in ruby with using something like `send("do_thing_to_#{some_class_name}")`. If I want to find uses of `do_thing_to_lesson`, then I'm not going to find this one easily.

I fully support your proposal!

**Comment by stevegrossi** [comment]
> The problem is that it makes it really hard to find a class

I have to agree with this one. I've been a big fan of the `&` usage in the past when I felt that avoiding repetition at all costs was the goal of a programmer, but in a world with "Select All" it's just as easy to rename a component like

```scss
.MyComponent { ... }
  .MyComponent-input { ... }
  .MyComponent--invalid { ... }
```

as it is to rename

```scss
.MyComponent {
  &-input { ... }
  &--invalid { ... }
}
```

And the former gives us the significant benefit of findability. Plus, deeply nested CSS is A Bad Thing<sup>[citation needed, but amirite?]</sup> that using `&` makes easier, and why would we want to do that?

**Comment by wsmd** [comment]
I like this too! Not only it's frustrating not to be able to find a selector when you search for, but also makes the code harder to read especially with long files.

I might also suggest that we _strictly allow nesting of pseudo classes and pseudo selectors only_ since they're not references in the markup. Anything else, like a SUITCSS a sub-component `&-` or a modifier `&--`, needs to be explicitly written. What do you all think?

**Comment by unixmonkey** [comment]
I mostly agree with the original post, though I do feel like the `&:hover` (and other pseudo selectors) are a valid case where I think we might want to continue using `&` (I could be convinced otherwise, though).

I've also had to use `&` recently to target style alterations based on the current language or locale, that I think are a useful abstraction, otherwise I'd have to put style overrides separately from the "default" style, like so:

With `&`:
```css
.MyComponent {
   width: 100px;
   margin-right: 2em;

   html[lang=de] & {
     width: 120px
   }
   html[dir=rtl] & {
      margin-right: 0;
      margin-left: 2em;
   }
}
```

Without `&`:
```css
.MyComponent {
   width: 100px;
   margin-right: 2em;
}
html[lang=de] .MyComponent {
  width: 120px;
}
html[dir=rtl] .MyComponent {
   margin-right: 0;
   margin-left: 2em;
}
```

This would look even worse targeting something deeply nested in a large stylesheet, and the style alternative/override could be far-away from the original, increasing the chance that it gets overlooked when styles get tweaked.

**Comment by wsmd** [comment]
I'd also argue that something `html[lang=de] &` can act like a pseudo class/selector since it's affecting the actual selector we're working with, so I don't see a problem with nesting those as well as it's nice to have them grouped in one place.

What's nested is very coupled and related to the selector itself:

```css
.MyComponent-input {
  &:nth-child(2n) { ... }
  &:hover { ... }
  &::before { ... }
  html[dir=rtl] & { ... }
}
```

**Comment by wuz** [comment]
I definitely agree on the `&:hover` pseudoclass stuff! I didn't make that very clear in my original post. I am a little hesitant on the `html[dir=rtl]` stuff, but not so much so that I couldn't be convinced.

My concern with those is that they are pretty easy to miss when you are scanning a file and it short-circuits some of the cascading nature of css. Using `html[dir=rtl] &` pulls you out of the local scope and creates a new global scope.

I can also see the argument that that block is a modifier, similar to how `&:hover` works. My preference is to maintain as much of the cascade as possible, which would just be

```scss
.MyComponent {
	.MyComponent-text {
		color: blue;
	}
}

html[dir=rtl] .MyComponent {
	.MyComponent-text {
		color: red;
	}
}

```

In that same vein, I don't like embedding media queries in CSS classes either, as that is another global scope inside of a local scope.

**Comment by unixmonkey** [comment]
I can relate to the hesitation, it doesn't feel like it should even work, but I think my concern of forcing all language/locale overrides being far-separated from the styles is pretty valid.

Even nested and close-by [like here](https://github.com/lessonly/lessonly/pull/6215/files#diff-0474ae1109f7d17bb239925c21f93295), it feels like it could still get overlooked.

Un-nested [like here](https://github.com/lessonly/lessonly/commit/2984fbd657be32fa050eeba2324105368384ae2c#diff-d3788bb367888ed1d085525bb676462c) feels even less likely to get noticed if someone went in and changed those styles, enough so that I'm considering refactoring this to be nested.

If you have any ideas to make this better, I'd love to explore it.

**Comment by wsmd** [comment]
> Un-nested feels even less likely to get noticed if someone went in and changed those styles, enough so that I'm considering refactoring this to be nested.

I second that! also with media queries. I feel that grouping everything related to a single selector in one place/level/scope/`{ ... }` has some good benefits. It's less like to get un-noticed like @unixmonkey said.

Having this sort of indentation and scoping helps me mentally that everything nested under a selector belongs to it and affects it, whether it's pseudo selectors,  pseudo elements, media-queries. I can for example, collapse that block, and now everything outside that block does not belong to the said selector. I also tend to find the following very helpful especially when _comparing_ the values that are changing under that selector:

```css
/* From a quick glance I can tell that I'm overwriting the color property of
MyComponent on mobile phones. */

.MyComponent {
  color: red;

  @media (max-width: $screen-phone) {
    color: yellow;
  }
}
```
